from src.clients.llm_client import JudgeResult
from src.clients.x_reverse_client import Tweet


def format_hiring_alert(tweet: Tweet, judge: JudgeResult) -> str:
	truncated_text = tweet.text[:400]
	suffix = "..." if len(tweet.text) > 400 else ""
	links_text = ", ".join(tweet.urls) if tweet.urls else "Check original tweet"

	return (
		"🚀 *SDE Intern Hiring Alert*\n\n"
		f"📍 *Company:* {judge.company or 'Not specified'}\n"
		f"💼 *Role:* {judge.role or 'SDE Intern'}\n"
		f"🌍 *Location:* {judge.location or 'Remote/Unspecified'}\n"
		f"🎯 *Confidence:* {judge.confidence:.0%}\n\n"
		f"📝 *Tweet by @{tweet.author_handle}:*\n"
		f"{truncated_text}{suffix}\n\n"
		f"🔗 *Links:* {links_text}\n\n"
		f"⏰ *Posted:* {tweet.created_at.strftime('%Y-%m-%d %H:%M UTC')}\n\n"
		"_Alert generated by Hiring Agent 🤖_"
	)


def format_daily_summary(seen_count: int, notified_count: int, errors: int) -> str:
	return (
		"📊 *Daily Hiring Agent Summary*\n\n"
		f"*Tweets Seen:* {seen_count}\n"
		f"*Alerts Sent:* {notified_count}\n"
		f"*Errors:* {errors}\n\n"
		"_End of summary_"
	)
